### ISSUE TITLE
500 Error on Sort on Some Columns e.g. Library Construction

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#170]
We are getting a back end 500 error like the below when sorting on library construction, specimen id, cell count. We need a ticket in the back end repo for this. 

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 212, in get_specimen_data
    index="ES_SPECIMEN_INDEX")
  File "/var/task/chalicelib/responseobjects/elastic_request_builder.py", line 489, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/var/task/elasticsearch_dsl/search.py", line 639, in execute
    **self._params
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/var/task/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'No mapping found for [libraryConstruction.keyword] in order to sort on')

┆Issue Number: HCAB-160

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspace/o/databiosphere/azul/issues/107
