### ISSUE TITLE
Bug preventing pages from going forward.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/data-browser#468]
I was just browsing https://integration.data.humancellatlas.org/explore/projects in firefox.

If you click on the bottom forward button for the next page of projects, it breaks on page 14/17 (clicking produces no further pages).  This produces the following error in the browser:
```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 726, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 355, in get_project_data
    entity_type='projects')
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 541, in transform_request
    final_response = FileSearchResponse(hits, paging, facets, entity_type)
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 649, in __init__
    KeywordSearchResponse.__init__(self, hits, entity_type)
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 568, in __init__
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 568, in <listcomp>
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 544, in map_entries
    for aggregate_file in entry["contents"]["files"]]
KeyError: 'files'
```

┆Issue Number: HCAB-383

**Comment by frano-m** [comment]
![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/86acda26-4bbd-4694-a1fa-67daa12be4b5)

**Comment by frano-m** [comment]
`https://service.integration.explore.data.humancellatlas.org/repository/projects?filters=%7B%7D&size=15&sort=projectTitle&order=asc&search_after=SS2%201%20Cell%20Integration%20Test&search_after_uid=doc%230dba9e42-c773-4fe2-aeb1-fc4c012f17e1`

^^ @theathorn request looks ok from our end - this is causing an error in azul

**Comment by hannes-ucsc** [comment]
There must be a project (outer entity) without files (inner entity). Step one is to figure out which specific project is causing this. My suspicion is that this is caused by a bug in the bundle deletion functionality.

**Comment by achave11-ucsc** [comment]
Further discussion [Azul](https://github.com/DataBiosphere/azul/issues/709).
